name: JSON Schema Validator
description: Validate JSON files against specified JSON schema
runs:
  using: docker
  image: Dockerfile
inputs:
  token:
    description: GitHub token to access pull request details
    required: true
  send_comment:
    description: Create a comment containing validation errors
    required: false
    default: "false"
  clear_comments:
    description: Clear previous error comment(s)
    required: false
    default: "false"
